### ISSUE TITLE
How do you integrate this into Laravel?

### ISSUE THREAD

**Issue by connecteev** [chenjiahan/vodal#19]
I like this package quite a lot.
However, I have an empty Laravel project and have been trying to install vodal into it, with no luck. I know the basics of vue.js but am still a beginner and have never used a Vue.js package in my laravel app before.

After running npm i -S vodal

Where does this code go? Help would be appreciated.

```
<vodal :show="show" animation="rotate" @hide="show = false">
    <div>A vue modal with animations.</div>
</vodal>
import Vue from 'vue';
import Vodal from 'vodal';

Vue.component(Vodal.name, Vodal);

export default {
  name: 'app',
    
  data() {
    return {
      show: false
    }
  }
}
// include animation styles
@import "vodal/common.css";
@import "vodal/rotate.css";

```

**Comment by chenjiahan** [comment]
Hi, I never used Vue in laravel before, but I found some blogs about that, maybe you can follow this guide.

https://blog.pusher.com/why-vuejs-laravel/

**Comment by connecteev** [comment]
@chenjiahan thank you, but I have vue.js working in Laravel. The challenge I am having is integrating vodal into Laravel. If you can get this working, any help would be appreciated!!

**Comment by chenjiahan** [comment]
Vodal is a vue component, so you just need to create a `.vue` file, import vodal and use it like other components.

**Comment by connecteev** [comment]
@chenjiahan 
I tried creating a .vue file but it did not work. I then went back to the drawing board, and I still haven't been able to get this to work. By the way, I did watch the 'component-related' videos at https://laracasts.com/series/learn-vue-2-step-by-step

Here is my public repo with the 2 commits of what I have tried: https://gitlab.com/connecteev/laravel_vodal_test

I ran this in Terminal 1: npm i -S vodal npm install npm run watch

I ran this in Terminal 2: php artisan serve This started serving at http://127.0.0.1:8000/ Then opened up a browser to go to http://127.0.0.1:8000/

Attempt 1: https://gitlab.com/connecteev/laravel_vodal_test/commit/d906e3c01e16dc74b8e5347808de90c1d2ef2639

This didnt work, and I then tried what I found here (for Attempt #2 below) https://vuejs.org/v2/guide/components-registration.html

Attempt 2: https://gitlab.com/connecteev/laravel_vodal_test/commit/7ee55b7d218d021729047a11ee229a3e3ce81460

No luck. All I see is https://prnt.sc/npion4

What am I missing?

**Comment by chenjiahan** [comment]
It seems that you didn't import the style of vodal correctly.

You should include `vodal.css` in your `app.css`

**Comment by connecteev** [comment]
You are right. That fixed the problem (among other changes I had to make to my welcome.blade.php file to include app.js and app.css)
Vodal is working great - thanks!
