### ISSUE TITLE
How to avoid aligning inner component center?

### ISSUE THREAD

**Issue by Symbolk** [chenjiahan/vodal#20]
I am embedding a monaco-editor in the vodal, however, all code in the editor are aligned center which is not expected, so I wonder how to avoid that?

Thanks for the nice lib and the reply!

**Comment by chenjiahan** [comment]
Vodal didn't set `text-align`, do you set `text-align: center` somewhere else?

**Comment by Symbolk** [comment]
Yeah, it turns out that I set it in my App.vue, which affects all children vue. I didn't find it because when I use another modal lib (https://github.com/euvl/vue-js-modal), it works properly. I guess that is because it overrides the text-align.
