### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by davidm-public** [chenjiahan/vodal#9]
thanks for the best modal library for vue!
other libraries, e.g: vue-js-modal are badly broken.
keep up the good work!

**Comment by chenjiahan** [comment]
My pleasure~ I will keep working on vodal. 😆

**Comment by danielbastos11** [comment]
@chenjiahan Thanks a lot, man!
Keep up the good work

**Comment by chenjiahan** [comment]
Sure~
